### ISSUE TITLE
Elbow Injuries Formatting Challenges

### ISSUE THREAD

**Issue by jvoros** [aliemteam/aliemcards#123]
@andyglittle what are you thinking for reformatting this card? It is so heavy on the table.

I the past I've turned the table header into list items to flatten it out:

```
|         | header 1 | header 2 | header 3 |
|-----|----------|----------|----------|
| one | value       | value       | value      |
| two | value       | value       | value      |

## One
- header 1: value
- header 2: value
- header 3: value

## Two
- header 1: value
- header 2: value
- header 3: value
```

I'm not sure that strategy works for this card.

**Comment by jvoros** [comment]
@michellealiem suggested maybe breaking this card up into smaller cards. As she points out, so much dense information isn't really "in a few words". 

Might make sense to break it up.

**Comment by jvoros** [comment]
I broke up the knee injuries card, and then made one main card to link to the other cards.

Check out this pull request to see how I did it:

#131

**Comment by andyglittle** [comment]
Starting to break up the elbow card now. In term of the images, what are
you using to crop the images from the current PDF Card to the github?

Andy

**Comment by jvoros** [comment]
I'm just using the screenshot tool on Mac to create an image.

There is probably something similar on Windows.

What are you using?

**Comment by andyglittle** [comment]
Mac, I'll give that a try

**Comment by jvoros** [comment]
Shift + Command + 4 will get you a crop box you can use to get just the
parts you want.

**Comment by andyglittle** [comment]
probably a stupid question, How to I get these into the github doc?

**Comment by andyglittle** [comment]
just tried it and I think I figured out. Let me know
