### ISSUE TITLE
EBM tag needs to be used appropriately

### ISSUE THREAD

**Issue by jvoros** [aliemteam/aliemcards#159]
EBM tag should relate to likelihood ratios, critical appraisals, meta-analyses, etc.

**Comment by dsifford** [comment]
@jvoros Devil's advocate: Even if the tags were used properly, would that be beneficial to the user?

In what scenario would somebody search `EBM` without context?

Perhaps this might be handy if we could search multiple tags at once, but we can't do that right now.

**Comment by jvoros** [comment]
Went through all the EBM cards. They are appropriately categorized.

I think they are useful to browse as a category. As a senior resident I often found myself discussing EBM itself, as a topic. Having a whole collection of cards on the topic is very useful. And there is little downside to having a single extra category.
