### ISSUE TITLE
Table format off in Blood Cultures card

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/aliemcards#194]
The bullet points are misaligned for Severity of Chills and Temperature.

![screen shot 2017-06-04 at 11 11 48 pm](https://cloud.githubusercontent.com/assets/15097022/26772589/4a115f56-497b-11e7-80fe-b305f85d0316.png)

**Comment by dsifford** [comment]
What's off about this?

**Comment by michellealiem** [comment]
The bullet points for Positive LR and Negative LR need to shift down one row.

**Comment by dsifford** [comment]
Ohhh... you mean like this?

![image](https://cloud.githubusercontent.com/assets/5240018/26791189/42dc2838-49e4-11e7-9c49-5e706909fa62.png)

Got it.

**Comment by michellealiem** [comment]
Aha nice sketching. Yes indeed!
