### ISSUE TITLE
API needs some sort of authorization for access

### ISSUE THREAD

**Issue by jvoros** [aliemteam/aliemcards#4]
Need some sort of security to limit access to approved client apps.

**Comment by jvoros** [comment]
Some resources:

- https://code.tutsplus.com/tutorials/creating-an-api-centric-web-application--net-23417
- https://scotch.io/tutorials/authenticate-a-node-js-api-with-json-web-tokens

**Comment by dsifford** [comment]
Closed somewhere near 6a5b667cfdf7729a35b2f9607e4f2922f28e392d
