### ISSUE TITLE
Make references at end consistent format

### ISSUE THREAD

**Issue by michellealiem** [aliemteam/aliemcards#42]
What I am thinking so far:
1. At the end of each post, list all the references in AMA format much like our blog posts with a Pubmed link (+/- link to an open access full text site, if available). Right now, some just have: First author, (no title), journal name, year, and PMID #.  We had to do that to save space for the 1-page goal.
2. Then we should probably have an additional reading section with AMA references following that

**Comment by dsifford** [comment]
@michellealiem Can you try to leave a helpful explanation of what you mean when creating issues? Possibly give an example of the change you're requesting if possible.

**Comment by michellealiem** [comment]
@dsifford - This was more of a to-do list item to make the references consistent. Not sure exactly what rec's I'm making beyond that. Maybe this doesn't belong in the Issues area? I can put on Slack instead?

**Comment by dsifford** [comment]
@michellealiem it's fine here, but just try to add even 1 or 2 sentences of context if you can. 

Specifically for this case: What consistent format are we targeting? Do you have an example of this format? Etc...

**Comment by michellealiem** [comment]
@dsifford - Ah I see.

OK so what I am thinking so far:
1. At the end of each post, list all the references in AMA format much like our blog posts with a Pubmed link (+/- link to an open access full text site, if available). Right now, some just have: First author, (no title), journal name, year, and PMID #.  We had to do that to save space for the 1-page goal.
2. Then we should probably have an additional reading section with AMA references following that

**Comment by jvoros** [comment]
All cards beginning with A are done.

Rest of the alphabet to go...

**Comment by dsifford** [comment]
Circling back to this @michellealiem (cc: @jvoros)

### First thoughts

> Then we should probably have an additional reading section with AMA references following that.

I disagree with this. I think that if the material is important enough, it should be referenced in the card itself.

### Reference format

Right now our format is AMA format with the entire reference being a clickable link. This is not in agreement with the blog, whose format is as follows:

```
1. <ama format citation>. PMID: <clickable link to pubmed surrounding the PMID if available>
```

Should we keep these consistent?


## Running list of cards that have improper references

(to be completed once I hear back about the agreed upon reference format)

**Comment by michellealiem** [comment]
Ah yes, thanks for reinvigorating this discussion. 
1. Agree with comment about leaving OFF "additional reading" section.
2. I like the idea of keeping the reference formatting similar to ALiEM site. Maybe it's just that I'm used to seeing this format where the PMID is the clickable link (rather than the title of the paper).

**Comment by dsifford** [comment]
@michellealiem I tend to agree with number 2, but I don't have particularly strong feelings there. Whichever way the team decides will work for me.

Thoughts @jvoros?

**Comment by jvoros** [comment]
Totally agree that it should be consistent with ALIEM site.

**Comment by jvoros** [comment]
Not all the references are PubMed references though.

Current blog reference format on recent posts is:

![screen shot 2017-05-09 at 12 48 29 am](https://cloud.githubusercontent.com/assets/2453798/25838631/54c908fc-3451-11e7-9a17-eaa3e2020a0e.png)

That gives some leeway as to what goes in the brackets, eg 'PubMed', 'URL', etc.

**Comment by jvoros** [comment]
I've written a little gulp script that converted the Reference link formatting. I am going through manually just to make sure there is no weirdness from the auto format. Just coming off an overnight, so it'll be this afternoon before I finish up.

**Comment by jvoros** [comment]
Got it pushed and in  PR #176 
There are still some nonconforming references. I've added them to the other REference issue: #127

**Comment by dsifford** [comment]
@jvoros I'm the one who wrote the plugin that makes those citations so I can tell you with confidence how it works 😝 

PubMed reference => [PubMed]
DOI, ISBN reference => [Source]
Reference with physical link in the title (so citing websites or blogs directly usually) => Doe, J. <this is the physical link which is now clickable>. _Nature_. [ ... etc ].

**Comment by dsifford** [comment]
Headed to class now. I'll look at what you got after I get out.

**Comment by dsifford** [comment]
Forgot to mention: if the literal doi is included in the reference (as I think it is with AMA format), then it is wrapped in a link and [Source] is skipped

**Comment by dsifford** [comment]
@jvoros Is this done now? I saw this: https://github.com/aliemteam/aliemcards/releases/tag/v0.5.4

**Comment by jvoros** [comment]
yes, complete.
