### ISSUE TITLE
Hyperlinks to blog posts need to be updated

### ISSUE THREAD

**Issue by jvoros** [aliemteam/aliemcards#98]
Hyperlinks need to point to correct blog post. Many have old URL.

**Comment by michellealiem** [comment]
And move the "Click [here] to read the full blog post" to the end of the post after references. Sometimes they are randomly in the middle of the post.

**Comment by dsifford** [comment]
This is the exact reason DOI was created 😛 

Such a pain to have to keep up with sites moving URLs and such. Wish we had that luxury!
